language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - sudo apt-get install unzip
  - wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/libtorrent/libtorrent-rasterbar-0.16.13.tar.gz
  - tar -xvf libtorrent-rasterbar-0.16.13.tar.gz
  - cd libtorrent-rasterbar-0.16.13
  - ./configure --enable-python-binding
  - make
  - make install
  - cd bindings/python
  - python setup.py build
  - python setup.py install
script:
  - python b.py
  - ls
