language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - sudo apt-get install python-libtorrent
  - sudo apt-get install deluge
  - sudo apt-get install deluge-webui

script:
  - python b.py
  - ls
