language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - sudo apt-get install unzip
  - sudo apt-get install -y aria2
  - mkdir downloads
  - cd downloads
  - sudo aria2c 'magnet:?xt=urn:btih:2F64EBEF1E816634E110FE4BFCBA06753CDC4B36&dn=Lil+Uzi+Vert+-+Eternal+Atake+%282020%29+%5B320+KBPS%5D&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2740%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fzephir.monocul.us%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.uw0.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce' --seed-time=0
  - 

script:
  - python up.py
  - ls
