language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - sudo apt-get install python-libtorrent

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
  - python b.py
  - ls
